# Generated by Django 3.0.5 on 2020-04-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0003_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('user_location', models.ManyToManyField(null=True, related_name='user_location', to='userapp.UserProfile')),
            ],
            options={
                'db_table': 'user_address',
            },
        ),
    ]
