# Generated by Django 3.0.5 on 2020-04-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='user_location',
            new_name='user_locations',
        ),
    ]
