# Generated by Django 3.0.5 on 2020-04-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_auto_20200427_1418'),
        ('post', '0003_auto_20200427_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='user_location',
            field=models.ManyToManyField(to='userapp.UserProfile'),
        ),
    ]
