# Generated by Django 3.0.5 on 2020-04-24 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0011_auto_20200424_1636'),
        ('userapp', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='userrole.UserRole'),
        ),
    ]
