# Generated by Django 3.0.5 on 2020-04-23 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0002_auto_20200423_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allpermission',
            name='permission_set',
        ),
    ]
