# Generated by Django 3.0.5 on 2020-04-23 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0003_remove_allpermission_permission_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='allpermission',
            name='permission_set',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='permission_set', to='userrole.PermissionGroup'),
            preserve_default=False,
        ),
    ]
