# Generated by Django 3.0.5 on 2020-04-23 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0004_allpermission_permission_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allpermission',
            name='permission_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_group', to='userrole.PermissionGroup'),
        ),
    ]
