# Generated by Django 3.0.5 on 2020-04-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0006_auto_20200423_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('permission', models.ManyToManyField(to='userrole.AllPermission')),
            ],
            options={
                'db_table': 'user_role',
            },
        ),
    ]
