# Generated by Django 3.0.5 on 2020-04-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0007_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='permission',
            field=models.ManyToManyField(related_name='permission', to='userrole.AllPermission'),
        ),
    ]
