# Generated by Django 3.0.5 on 2020-04-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userrole', '0009_auto_20200424_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='permission',
            field=models.ManyToManyField(blank=True, null=True, related_name='permission', to='userrole.AllPermission'),
        ),
    ]
